@startuml system heat house
title Система "Теплый дом" [System Context]

top to bottom direction

!include C4_Context.puml

Person(user, "Пользователь", "Имеет регистрацию в системе по номеру телефона")

System(monolith, "Приложение", "Позволяет пользователю управлять своими устройствами и получать температуру со своих датчиков")

System_Ext(devices, "Устройства", "Включают или выключают отопление и выдают данные о температуре")

System_Ext(sms, "СМС-шлюз", "Отправляет смс на номер телефона")

Rel(user, monolith, "Авторизация по СМС, просмотр своих устройств, управление ими и получение температуры с них")

Rel(monolith, sms, "Отправление СМС с кодом авторизации")

Rel(sms, user, "Получение кода авторизации в СМС")

Rel(monolith, devices, "Управление и получения данных")


@enduml
